<x-layouts::app :title="__('Certificates Management')">

    <style>
        .pw-card {
            background: #ffffff;
            border: 1px solid #e7e9ef;
            border-radius: 20px;
            box-shadow: 0 1px 3px rgba(15, 23, 42, 0.035);
        }
    </style>

    <div class="min-h-screen bg-[#f8f9fc]">

        <main class="px-5 py-7 sm:px-6 lg:px-8 lg:py-9">

            <div class="mx-auto max-w-[1500px]">


                {{-- =====================================================
                    HEADER
                ====================================================== --}}

                <div class="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">

                    <div>

                        <p class="text-xs font-bold uppercase tracking-[.12em] text-violet-600">
                            Academic Records
                        </p>

                        <h1 class="mt-2 text-3xl font-bold tracking-tight text-slate-950">
                            Certificates Management
                        </h1>

                        <p class="mt-2 max-w-2xl text-sm leading-6 text-slate-500">
                            View all certificates generated by students.
                        </p>

                    </div>

                </div>



                {{-- =====================================================
                    CERTIFICATES TABLE
                ====================================================== --}}

                <section class="pw-card mt-7 overflow-hidden">

                    <div class="overflow-x-auto">

                        <table class="w-full min-w-[700px] text-left text-sm">

                            <thead class="border-b border-slate-100 bg-slate-50/80">

                                <tr class="text-[10px] font-bold uppercase tracking-[.08em] text-slate-400">

                                    <th class="px-6 py-4">Certificate No.</th>
                                    <th class="px-6 py-4">Student</th>
                                    <th class="px-6 py-4">Course</th>
                                    <th class="px-6 py-4">Issued Date</th>

                                </tr>

                            </thead>


                            <tbody class="divide-y divide-slate-100">

                                @forelse($certificates as $certificate)

                                    <tr class="transition hover:bg-slate-50/70">

                                        <td class="px-6 py-5">

                                            <span class="inline-flex items-center rounded-lg bg-violet-50 px-3 py-1.5 text-xs font-bold text-violet-700">
                                                {{ $certificate->certificate_number }}
                                            </span>

                                        </td>

                                        <td class="px-6 py-5">

                                            <div class="flex items-center gap-3">

                                                <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-violet-100 text-xs font-bold text-violet-700">
                                                    {{ strtoupper(substr($certificate->student->name ?? 'S', 0, 1)) }}
                                                </div>

                                                <p class="text-sm font-semibold text-slate-800">
                                                    {{ $certificate->student->name ?? '-' }}
                                                </p>

                                            </div>

                                        </td>

                                        <td class="px-6 py-5 text-sm text-slate-600">
                                            {{ $certificate->course->title ?? '-' }}
                                        </td>

                                        <td class="px-6 py-5 text-xs font-semibold text-slate-600">
                                            {{ $certificate->created_at->format('M d, Y') }}
                                        </td>

                                    </tr>

                                @empty

                                    <tr>

                                        <td colspan="4" class="px-6 py-16 text-center">

                                            <div class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-violet-50 text-violet-600">

                                                <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                                    <rect x="3" y="5" width="18" height="14" rx="2"/>
                                                    <path d="M3 10h18"/>
                                                    <path d="M7 15h3"/>
                                                    <circle cx="15" cy="15" r="1"/>
                                                </svg>

                                            </div>

                                            <h3 class="mt-4 text-sm font-bold text-slate-800">
                                                No certificates found
                                            </h3>

                                            <p class="mt-1 text-xs text-slate-400">
                                                Certificates will appear here once students complete courses.
                                            </p>

                                        </td>

                                    </tr>

                                @endforelse

                            </tbody>

                        </table>

                    </div>


                    {{-- PAGINATION --}}
                    @if($certificates->hasPages())

                        <div class="border-t border-slate-100 px-6 py-4">
                            {{ $certificates->links() }}
                        </div>

                    @endif

                </section>

            </div>

        </main>

    </div>

</x-layouts::app>