<x-layouts::app :title="__('Certificates Management')">
    <div class="space-y-6">

        <div>
            <h1 class="text-3xl font-bold text-white">
                Certificates Management
            </h1>
            <p class="text-sm text-gray-400">
                View all certificates generated by students.
            </p>
        </div>

        <div class="rounded-2xl border border-neutral-700 bg-neutral-900 p-6 shadow-lg shadow-purple-950/10">

            <div class="overflow-x-auto">
                <table class="w-full text-left text-sm">
                    <thead class="bg-neutral-800 text-xs uppercase tracking-wider text-white">
                        <tr>
                            <th class="px-6 py-4">Certificate No.</th>
                            <th class="px-6 py-4">Student</th>
                            <th class="px-6 py-4">Course</th>
                            <th class="px-6 py-4">Issued Date</th>
                        </tr>
                    </thead>

                    <tbody class="divide-y divide-neutral-800">
                        @forelse($certificates as $certificate)
                            <tr class="hover:bg-white/5">
                                <td class="px-6 py-4 font-semibold text-white">
                                    {{ $certificate->certificate_number }}
                                </td>

                                <td class="px-6 py-4 text-gray-400">
                                    {{ $certificate->student->name ?? '-' }}
                                </td>

                                <td class="px-6 py-4 text-gray-400">
                                    {{ $certificate->course->title ?? '-' }}
                                </td>

                                <td class="px-6 py-4 text-gray-400">
                                    {{ $certificate->created_at->format('M d, Y') }}
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4" class="px-6 py-16 text-center">
                                    <h3 class="text-lg font-semibold text-white">No certificates found</h3>
                                    <p class="mt-1 text-sm text-gray-400">
                                        Certificates will appear here once students complete courses.
                                    </p>
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            <div class="mt-4">
                {{ $certificates->links() }}
            </div>

        </div>

    </div>
</x-layouts::app>