<x-layouts::app :title="'Course Students'">
@php
    $averageProgress = $enrollments->count() ? $enrollments->avg('progress_percentage') : 0;
    $completed = $enrollments->where('status', 'completed')->count();
    $active = $enrollments->where('status', 'active')->count();
@endphp
<div class="min-h-screen bg-slate-50/80 pb-12 text-slate-900">
    <div class="border-b border-slate-200 bg-white">
        <div class="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8">
            <nav class="flex items-center gap-2 text-xs font-semibold text-slate-400"><a href="{{ route('teacher.my-courses') }}" class="hover:text-violet-700">My Courses</a><span>›</span><span class="max-w-52 truncate">{{ $course->title }}</span><span>›</span><span class="text-violet-600">Students</span></nav>
            <div class="mt-5 flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
                <div class="flex min-w-0 items-center gap-4">
                    <div class="h-20 w-28 shrink-0 overflow-hidden rounded-2xl bg-gradient-to-br from-violet-600 to-indigo-600">@if($course->thumbnail)<img src="{{ asset('storage/'.$course->thumbnail) }}" class="h-full w-full object-cover" alt="">@else<div class="flex h-full items-center justify-center text-3xl font-black text-white">{{ strtoupper(substr($course->title,0,1)) }}</div>@endif</div>
                    <div class="min-w-0"><p class="text-xs font-bold uppercase tracking-[0.18em] text-violet-600">Course Students</p><h1 class="mt-2 truncate text-2xl font-black text-slate-950 sm:text-3xl">{{ $course->title }}</h1><p class="mt-1 text-sm text-slate-500">Track learner progress and open individual lesson activity.</p></div>
                </div>
                <div class="flex gap-2"><a href="{{ route('teacher.lessons',$course) }}" class="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 hover:border-violet-200 hover:text-violet-700">Manage Lessons</a><a href="{{ route('teacher.courses.edit',$course) }}" class="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-violet-700">Edit Course</a></div>
            </div>
        </div>
    </div>
    <div class="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
        <div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Enrolled</p><p class="mt-2 text-3xl font-black">{{ $enrollments->count() }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Avg. progress</p><p class="mt-2 text-3xl font-black text-violet-600">{{ number_format($averageProgress,0) }}%</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Active</p><p class="mt-2 text-3xl font-black text-blue-600">{{ $active }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Completed</p><p class="mt-2 text-3xl font-black text-emerald-600">{{ $completed }}</p></div></div>
        <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="text-lg font-extrabold text-slate-950">Enrolled students</h2><p class="mt-1 text-sm text-slate-500">Open a learner to see progress lesson by lesson.</p></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Student</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Enrolled</th><th class="px-5 py-4">Progress</th><th class="px-5 py-4 text-right">Action</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($enrollments as $enrollment)@php $done=$enrollment->status==='completed'; @endphp<tr class="hover:bg-slate-50/70"><td class="px-5 py-4"><div class="flex items-center gap-3"><div class="flex h-10 w-10 items-center justify-center rounded-full bg-violet-50 text-sm font-black text-violet-700">{{ strtoupper(substr($enrollment->student->name,0,1)) }}</div><div><p class="font-bold text-slate-900">{{ $enrollment->student->name }}</p><p class="text-xs text-slate-400">{{ $enrollment->student->email }}</p></div></div></td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-bold {{ $done?'bg-emerald-50 text-emerald-700':'bg-blue-50 text-blue-700' }}">{{ ucfirst($enrollment->status) }}</span></td><td class="px-5 py-4 text-slate-500">{{ optional($enrollment->enrolled_at)->format('M d, Y') ?? '—' }}</td><td class="px-5 py-4"><div class="flex min-w-48 items-center gap-3"><div class="h-2 flex-1 rounded-full bg-slate-100"><div class="h-2 rounded-full {{ $done?'bg-emerald-500':'bg-violet-500' }}" style="width:{{ min($enrollment->progress_percentage??0,100) }}%"></div></div><span class="w-12 text-right font-bold text-slate-700">{{ number_format($enrollment->progress_percentage??0,0) }}%</span></div></td><td class="px-5 py-4 text-right"><a href="{{ route('teacher.student.progress',[$course,$enrollment->student]) }}" class="inline-flex rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700 hover:border-violet-200 hover:bg-violet-50 hover:text-violet-700">View progress</a></td></tr>@empty<tr><td colspan="5" class="px-6 py-14 text-center text-sm text-slate-400">No students are enrolled in this course yet.</td></tr>@endforelse</tbody></table></div></div>
    </div>
</div>
</x-layouts::app>
