<x-layouts::app :title="'Student Progress'">
@php
    $completedLessons = $lessons->filter(fn($lesson) => optional($progressByLesson->get($lesson->id))->status === 'completed')->count();
@endphp
<div class="min-h-screen bg-slate-50/80 pb-12 text-slate-900">
    <div class="border-b border-slate-200 bg-white"><div class="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><a href="{{ route('teacher.course.students',$course) }}" class="text-sm font-semibold text-slate-500 hover:text-violet-700">← Back to course students</a><div class="mt-5 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-violet-600">Learner Detail</p><h1 class="mt-2 text-3xl font-black text-slate-950">{{ $student->name }}</h1><p class="mt-1 text-sm text-slate-500">{{ $course->title }}</p></div><div class="rounded-2xl bg-violet-50 px-5 py-4 text-right"><p class="text-xs font-bold uppercase text-violet-500">Overall progress</p><p class="mt-1 text-3xl font-black text-violet-700">{{ number_format($enrollment->progress_percentage??0,0) }}%</p></div></div></div></div>
    <div class="mx-auto max-w-6xl space-y-6 px-4 py-8 sm:px-6 lg:px-8"><div class="grid grid-cols-2 gap-3 md:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase text-slate-400">Lessons</p><p class="mt-2 text-3xl font-black">{{ $lessons->count() }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase text-slate-400">Completed</p><p class="mt-2 text-3xl font-black text-emerald-600">{{ $completedLessons }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase text-slate-400">Status</p><p class="mt-2 text-xl font-black capitalize {{ $enrollment->status==='completed'?'text-emerald-600':'text-blue-600' }}">{{ $enrollment->status }}</p></div></div>
        <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="text-lg font-extrabold text-slate-950">Lesson activity</h2><p class="mt-1 text-sm text-slate-500">Every lesson is listed, including lessons the student has not started yet.</p></div><div class="divide-y divide-slate-100">@forelse($lessons as $lesson)@php $item=$progressByLesson->get($lesson->id); $status=$item->status??'not_started'; @endphp<div class="grid gap-3 px-5 py-4 md:grid-cols-[52px_1fr_150px_130px] md:items-center"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-sm font-black text-slate-500">{{ str_pad($lesson->lesson_order,2,'0',STR_PAD_LEFT) }}</div><div><p class="font-bold text-slate-900">{{ $lesson->title }}</p><p class="mt-1 text-xs capitalize text-slate-400">{{ $lesson->lesson_type }}{{ $lesson->duration_minutes?' · '.$lesson->duration_minutes.' min':'' }}</p></div><div><span class="rounded-full px-3 py-1 text-xs font-bold {{ $status==='completed'?'bg-emerald-50 text-emerald-700':($status==='in_progress'?'bg-blue-50 text-blue-700':'bg-slate-100 text-slate-500') }}">{{ str_replace('_',' ',ucfirst($status)) }}</span></div><div class="text-xs text-slate-500">{{ $item?->completed_at ? \Carbon\Carbon::parse($item->completed_at)->format('M d, Y') : '—' }}</div></div>@empty<div class="px-6 py-14 text-center text-sm text-slate-400">This course has no lessons yet.</div>@endforelse</div></div>
    </div>
</div>
</x-layouts::app>
