<x-layouts::app :title="__('Student Progress')">
@php
    $totalEnrollments=$enrollments->count(); $completed=$enrollments->where('status','completed')->count(); $active=$enrollments->where('status','active')->count(); $averageProgress=$totalEnrollments?$enrollments->avg('progress_percentage'):0;
@endphp
<div class="min-h-screen bg-slate-50/80 pb-12 text-slate-900">
    <div class="border-b border-slate-200 bg-white"><div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><p class="text-xs font-bold uppercase tracking-[0.2em] text-violet-600">Learner Analytics</p><h1 class="mt-2 text-3xl font-black tracking-tight text-slate-950">Student Progress</h1><p class="mt-2 text-sm text-slate-500">Monitor enrollment status and course completion across your learners.</p></div></div>
    <div class="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
        <div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Enrollments</p><p class="mt-2 text-3xl font-black">{{ $totalEnrollments }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Active</p><p class="mt-2 text-3xl font-black text-blue-600">{{ $active }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Completed</p><p class="mt-2 text-3xl font-black text-emerald-600">{{ $completed }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Avg. progress</p><p class="mt-2 text-3xl font-black text-violet-600">{{ number_format($averageProgress,1) }}%</p></div></div>
        <form method="GET" class="grid gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm md:grid-cols-[1fr_260px_170px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Search student name or email" class="h-11 rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none focus:border-violet-400 focus:ring-4 focus:ring-violet-100"><select name="course" class="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-violet-400 focus:ring-4 focus:ring-violet-100"><option value="all">All courses</option>@foreach($courses as $course)<option value="{{ $course->id }}" @selected((string)request('course')===(string)$course->id)>{{ $course->title }}</option>@endforeach</select><select name="status" class="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-violet-400 focus:ring-4 focus:ring-violet-100"><option value="all">All status</option><option value="active" @selected(request('status')==='active')>Active</option><option value="completed" @selected(request('status')==='completed')>Completed</option></select><button class="h-11 rounded-xl bg-slate-900 px-5 text-sm font-bold text-white">Filter</button></form>
        <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="text-lg font-extrabold text-slate-950">Enrollment progress</h2><p class="mt-1 text-sm text-slate-500">Progress by student and course.</p></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Student</th><th class="px-5 py-4">Course</th><th class="px-5 py-4">Progress</th><th class="px-5 py-4">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($enrollments as $enrollment)@php $progress=$enrollment->progress_percentage??0; $done=strtolower($enrollment->status??'active')==='completed'; @endphp<tr class="hover:bg-slate-50/70"><td class="px-5 py-4"><div class="flex items-center gap-3"><div class="flex h-9 w-9 items-center justify-center rounded-full bg-violet-50 text-sm font-black text-violet-700">{{ strtoupper(substr($enrollment->student->name??'S',0,1)) }}</div><div><p class="font-bold text-slate-900">{{ $enrollment->student->name??'Student' }}</p><p class="text-xs text-slate-400">{{ $enrollment->student->email??'' }}</p></div></div></td><td class="px-5 py-4"><p class="font-semibold text-slate-800">{{ $enrollment->course->title??'Course' }}</p><p class="text-xs text-slate-400">{{ $enrollment->course->category->name??'General' }}</p></td><td class="px-5 py-4"><div class="flex min-w-48 items-center gap-3"><div class="h-2 flex-1 rounded-full bg-slate-100"><div class="h-2 rounded-full {{ $done?'bg-emerald-500':'bg-violet-500' }}" style="width:{{ min($progress,100) }}%"></div></div><span class="w-12 text-right font-bold text-slate-700">{{ number_format($progress,0) }}%</span></div></td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-bold {{ $done?'bg-emerald-50 text-emerald-700':'bg-blue-50 text-blue-700' }}">{{ $done?'Completed':'Active' }}</span></td></tr>@empty<tr><td colspan="4" class="px-6 py-14 text-center text-sm text-slate-400">No student progress matches the current filters.</td></tr>@endforelse</tbody></table></div></div>
    </div>
</div>
</x-layouts::app>
